version: '3.4'

networks: 
  prometheus-net:
    driver: bridge

services:


  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./volumes/alertmanager:/config"
    command: --config.file=/config/alertmanager.yml --log.level=debug
    networks:
      - prometheus-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - prometheus-net
    restart: always
    volumes: 
      - ./volumes/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus/config/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports: 
      - 9090:9090

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: always
      
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    container_name: grafana
    networks:
      - prometheus-net
    restart: always
    volumes: 
      - ./grafana/provisioning/:/etc/grafana/provisioning
    ports:
      - 3000:3000