global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - ./alert.rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ '192.168.43.74:9093' ]

scrape_configs:
  - job_name: 'prometheus' 
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
    static_configs:
      - targets: ['192.168.43.74:9090','kong:8001','192.168.43.74:8001']

  - job_name: 'Fast-api'
    static_configs:
      - targets: ['192.168.43.74:8097']

  - job_name: mysql_DB
    static_configs:
      - targets: ['192.168.43.74:3306']

  - job_name: 'pushgateway'
    honor_labels: true
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets:
          - '192.168.43.74:9091'